document.writeln(`<h3> ${navigator.appName}</h3>`)
document.writeln(`<h3> ${navigator.appCodeName}</h3>`)
document.writeln(`<h3> ${navigator.appVersion}</h3>`)
document.writeln(`<h3> ${navigator.cookieEnabled}</h3>`)
document.writeln(`<h3> ${navigator.userAgent}</h3>`)
document.writeln(`<h3> ${navigator.language}</h3>`)
document.writeln(`<h3> ${navigator.platform}</h3>`)
document.writeln(`<h3> ${navigator.online}</h3>`)